default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nature_remo_local_development

test:
  <<: *default
  database: nature_remo_local_test

production:
  <<: *default
  database: nature_remo_local_production
  username: nature_remo_local
  password: <%= ENV['NATURE_REMO_LOCAL_DATABASE_PASSWORD'] %>
